#!/usr/bin/env python3
# © 2023 Erik Ben Heckman (https://github.com/heckman) <erik@heckman.ca>
# License: MIT

# eml2text
#
# v0.2
#
# takes the name of an eml file as its only argument
# and prints the body of the email as plain-text to stdout

from email import policy,  message_from_file
from sys import argv, exit, stderr

try:
    with open(argv[1]) as fp:
        message=message_from_file(fp, policy=policy.default)
        print(f"""Date: {message["date"]}
From: {message["from"]}
To: {message["to"]}
Subject: {message["subject"]}

{message.get_body(preferencelist=('plain',)).get_content()}""")

except OSError as e:
    print(f"Unable to open {argv[1]}", file=stderr)
    exit(1)

except IndexError as e:
    print(F"Usage: {argv[0]} <EML_FILE>")
    exit(1)
